CREATE DATABASE inventory;
USE inventory;

CREATE TABLE users(
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(100) UNIQUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products(
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100),
 price FLOAT NOT NULL
);

CREATE TABLE inventory(
 id INT AUTO_INCREMENT PRIMARY KEY,
 product_id INT,
 quantity INT,
 FOREIGN KEY(product_id) REFERENCES products(id)
);

CREATE TABLE orders(
 id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE order_items(
 id INT AUTO_INCREMENT PRIMARY KEY,
 order_id INT,
 product_id INT,
 quantity INT,
 FOREIGN KEY(order_id) REFERENCES orders(id),
 FOREIGN KEY(product_id) REFERENCES products(id)
);